---
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: trailing-whitespace
        exclude_types: [svg]

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade
        args: ["--py38-plus", "--keep-runtime-typing"]
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [-j8]
        additional_dependencies:
          - flake8-broken-line
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-isort
          - flake8-black

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.11.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        types_or: [python, rst, markdown]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types: [yaml]
